### PR TITLE
3.5.5 bugfixes 2

### PR DESCRIPTION
**Pull request by NikkoJT**
There are more I guess

### CODE REVIEW

**Review by shadow-fa — APPROVED** [review]
looks good

**Review by darkChozo — APPROVED** [review]
We should probably hold a multiplayer test of the new cascap system before releasing 3.5.5 (I can add it to the test mission). Also we should probably avoid merging new stuff until release, to avoid more stuff like this.

**Comment by NikkoJT** [comment]
We can't get to a release-ready state without merging stuff to dev. Merging to dev and then testing from dev branch is part of the release checklist. Of course, this ideally should have been caught before then, but the point of dev branch is to catch things like this before release.

Also, we have been sitting on this update for like six months after it was originally supposed to be out (remember that "new faster release schedule"?) and I would very much like to have it out before the end of the month. Or at least before the end of the year.

**Comment by darkChozo** [comment]
I mean merging completely new stuff. This bug was introduced with the cascap changes, which I believed were PRed and merged after the initial round of 3.5.5 testing. We'd likely be able to release now if dev had been frozen to new changes.

**Comment by NikkoJT** [comment]
This is a fix for an issue with a cascap change that is no longer being included in 3.5.5. @shadow-fa should make sure this fix is included in the version of the cascap change that eventually gets released; this PR will be closed without merging.

**Pull request closed without merging**
