### PR TITLE
Add Mission Condition Notes

### PR DESCRIPTION
**Pull request by darkChozo**
Adds a briefing page summarizing mission conditions.

Also fixes a bug with setTime. (was erroring on evening)

https://github.com/folkarps/F3/issues/222

### CODE REVIEW

**Comment by darkChozo** [comment]
Ran everything through sqflint, fixed what it found (though it doesn't recognize the `#` operator which was causing a lot of false warnings). Also you forced me to download Atom so good job there.

Moon phase does have a rather significant effect on overall brightness, though obviously it depends on how well your set up deals with dark scenes. On a clear night, a new moon is effectively pitch black, while a full moon is bright enough on my setup to get around reasonably without NVGs. Again, YMMV.

I believe that both Nikko and I have used setAperture to brighten up dark missions without any issues (Occupational Exposure and Priority Air from me, Once More With Feeling from Nikko). I don't think the setting is universal enough to handle automatically, and it's literally a one liner so I'm not sure how much you could do as far as integrating it as an optional component goes. I guess you could try to autodetect map/weather and set aperture appropriately?

**Comment by shadow-fa** [comment]
> Also you forced me to download Atom so good job there.

SQF linters are also available as standalone software and there's also plugins for other editors like VS Code ;)

re aperture: I was thinking a seperate "time of day" option for f3 parameters for "bright night" or something.

**Comment by darkChozo** [comment]
A brighter night setting might make sense, the only thing is that I'm not sure if there are aperture settings that look good in any condition. Probably something for another issue though.

**Comment by darkChozo** [comment]
see #306

**Pull request closed without merging**
