### PR TITLE
Orbat: Marker for specialists and cargo

### PR DESCRIPTION
**Pull request by shadow-fa**
#### Changes:
* Add markers for specialists and cargo slots
* Add compatibility for singleplayer mode
* Add helper function `_fnc_getMarker` to cut down on duplicate code

#### What it looked like previously:
Capture2
Vehicles:
image

#### What it looks like now:
Capture
Vehicles:
Capture3

#### Open question:
If a vehicle only has units from a single group, do we want to only show the marker for the vehicle and not for the individual slots?

### CODE REVIEW

**Comment by NikkoJT** [comment]
No objections to specialist markers.

> If a vehicle only has units from a single group, do we want to only show the marker for the vehicle and not for the individual slots?

I think that's a good idea. Also, how plausible is it to create a separation between crew and passenger slots for this purpose? In the IFV example I'm concerned that the whole crew having markers could give the impression that they're all in different teams.

**Comment by shadow-fa** [comment]
>  create a separation between crew and passenger slots for this purpose?

Is the [CARGO] thing we've always had not enough for that purpose?

> In the IFV example I'm concerned that the whole crew having markers could give the impression that they're all in different teams.

On the other hand, in the HEMTT example it might be misleading if we just give the marker to the vehicle itself. Does the vehicle really belong to Alpha? (See examples below)

Possible alternatives:
A: 
image

B: 
image

**Comment by NikkoJT** [comment]
> Is the [CARGO] thing we've always had not enough for that purpose?

I meant for the purposes of deciding which markers to be displayed. Take an IFV. It would have all the crew as one group (AV) but potentially multiple groups in the vehicle overall (A1, ASL).

> If a vehicle only has units from a single group, do we want to only show the marker for the vehicle and not for the individual slots?

So we would want to show only one marker for the crew, since they're all in one group, but at the same time also show the markers for different groups that are only in  cargo seats. However, it seems like your examples have this covered.

> On the other hand, in the HEMTT example it might be misleading if we just give the marker to the vehicle itself. Does the vehicle really belong to Alpha? (See examples below)
> 
> Possible alternatives:

I like A.

**Comment by SamLex** [comment]
@shadow-fa Could you please add a 'before' equivalent of the vehicle screenshot in the top comment?

**Comment by shadow-fa** [comment]
> @shadow-fa Could you please add a 'before' equivalent of the vehicle screenshot in the top comment?

Done

**Pull request merged**
